### ISSUE TITLE
【リファクタリング】画像のURLパラメータはデータプロパティに定義する

### ISSUE THREAD

**Issue by bami55** [RocketLeagueJapanDevelopersCommunity/rl-japan.com#139]
## 関連
#137 のコードを見ていて思った

## 内容
画像のURLパラメータはデータプロパティ（ `data` ）に定義して、画像のURLを算出プロパティ（ `computed` ）で生成させたほうがよさそう。
今後変更する際もそのほうが分かりやすく、変更漏れなども防ぎやすい。

### components/Writer.vueの場合
- fit=crop
- w=100
- h=100
- q=85
- fm=webp

https://github.com/RocketLeagueJapanDevelopersCommunity/rl-japan.com/blob/93c64057bfe3daa0c51bf49faa6cba6fa035a1c2/components/Writer.vue#L5-L15

## 対象のコンポーネント
- [Writer](https://github.com/RocketLeagueJapanDevelopersCommunity/rl-japan.com/blob/develop/components/Writer.vue)
- [Partner](https://github.com/RocketLeagueJapanDevelopersCommunity/rl-japan.com/blob/develop/components/Partner.vue)

**Comment by karuhi** [comment]
色々なとこで雑に定義してあるので、utilかなんかでまとめてあげたい。。

**Comment by bami55** [comment]
URLSearchParamsを使うと良さげ
[JavaScriptでクエリ付きURLを簡単に作る（URLSearchParams）](https://zenn.dev/naoki_oshiumi/articles/be8e3ba99d0788)
