### ISSUE TITLE
【フッタの関連記事】Meta情報の下部の余白が小さい

### ISSUE THREAD

**Issue by bami55** [RocketLeagueJapanDevelopersCommunity/rl-japan.com#61]
●更新情報や日付の上部の余白と同じくらい、下部の余白を増やすと自然に見えるのでは。
![image](https://user-images.githubusercontent.com/3437810/176941408-589f8091-acf2-4196-8243-32ab6fb0be47.png)

**Comment by karuhi** [comment]
![image](https://user-images.githubusercontent.com/15998572/219935209-151178f0-8b53-4106-9e50-db18ba049021.png)

**Comment by karuhi** [comment]
一旦以上で本番反映してみた～～～

**Comment by bami55** [comment]
余白が小さい件は解消されたのでクローズしま
